POST http://localhost:3000/load-admin
Content-Type: application/json

{
    "name": "nguyen van a",
    "password": "nguyenvana"
}

###
GET http://localhost:3000/load-room/6700b4a9c4cf07fcd3b47f17

###
GET http://localhost:3000/load-user/66fe5187a9353691ce7065ce

###
POST http://localhost:3000/add-user
Content-Type: application/json

{
    "name": "nguyen van c",
    "password": "nguyenvanc"
}

###
GET http://localhost:3000