POST http://localhost:3000/load-admin
Content-Type: application/json

{
    "name": "nguyen van a",
    "password": "nguyenvana"
}

###
GET http://localhost:3000/load-room/66fe5298a9353691ce7065d2

###
GET http://localhost:3000/load-user/66fe5187a9353691ce7065ce

###
GET http://localhost:3000