
GET http://localhost:3000/room/get-room/6708ad9111ff219c7057fe36
###
POST http://localhost:3000/room/create-room
Content-Type: application/json

{
    "name": "",
    "password": ""
}

###
POST http://localhost:3000/room/join-room
Content-Type: application/json

{
    "user_id": "6708fbe13cd993f13fb0b373",
    "room_id": "6708ad9111ff219c7057fe36"
}