POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "nguyenvana@gmail.com",
    "password": "nguyenvana"
}

###
GET http://localhost:3000/user/get-user/6708ad2b11ff219c7057fe30

###
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "name": "nguyen van d",
    "email": "nguyenvand@gmail.com",
    "password": "nguyenvand"
}
